[project]
name = "pycaff"
version = "1.0.0"
description = "Caffeinate for Windows that uses PowerPlan "
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "pystray>=0.19.5",
]
